### ISSUE TITLE
io.vamp.common.notification.Notification | Future times out after 30 seconds

### ISSUE THREAD

**Issue by shaluz** [magneticio/vamp-router#24]
Hi,
I am new to Vamp and Docker. Sorry if this is a silly mistake from my side. Can someone tell me why do I get this error and the solution for the same:

| ERROR | akka.actor.OneForOneStrategy             | e/user/deployment-synchronization-actor$ | Futures timed out after [30 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169) ~[vamp-core.jar:0.7.10]
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [vamp-core.jar:0.7.10]
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.Await$.ready(package.scala:169) ~[vamp-core.jar:0.7.10]
    at io.vamp.common.akka.FutureSupport$class.offload(FutureSupport.scala:12) ~[vamp-core.jar:0.7.10]
    at io.vamp.core.operation.deployment.DeploymentSynchronizationActor.offload(DeploymentSynchronizationActor.scala:44) ~[vamp-core.jar:0.7.10]
    at io.vamp.core.operation.deployment.DeploymentSynchronizationActor.io$vamp$core$operation$deployment$DeploymentSynchronizationActor$$synchronize(DeploymentSynchronizationActor.scala:88) ~[vamp-core.jar:0.7.10]
    at io.vamp.core.operation.deployment.DeploymentSynchronizationActor$$anonfun$receive$1.applyOrElse(DeploymentSynchronizationActor.scala:73) ~[vamp-core.jar:0.7.10]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[vamp-core.jar:0.7.10]
    at io.vamp.core.operation.deployment.DeploymentSynchronizationActor.aroundReceive(DeploymentSynchronizationActor.scala:44) ~[vamp-core.jar:0.7.10]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [vamp-core.jar:0.7.10]
    at akka.actor.ActorCell.invoke(ActorCell.scala:487) [vamp-core.jar:0.7.10]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [vamp-core.jar:0.7.10]
    at akka.dispatch.Mailbox.run(Mailbox.scala:220) [vamp-core.jar:0.7.10]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [vamp-core.jar:0.7.10]
09:22:07.350 api NOTI ==>  GET   /v1/routes                                         200     15.398µs 
09:22:07.435 | ERROR | io.vamp.common.notification.Notification |                                          | Container response error.
09:22:07.436 | ERROR | io.vamp.common.notification.Notification |                                          | Futures timed out after [30 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169) ~[vamp-core.jar:0.7.10]
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [vamp-core.jar:0.7.10]
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167) ~[vamp-core.jar:0.7.10]
    at scala.concurrent.Await$.ready(package.scala:169) ~[vamp-core.jar:0.7.10]
    at io.vamp.common.akka.FutureSupportNotification$class.offload(FutureSupport.scala:24) ~[vamp-core.jar:0.7.10]
    at io.vamp.core.container_driver.ContainerDriverActor.offload(ContainerDriverActor.scala:29) [vamp-core.jar:0.7.10]
    at io.vamp.core.container_driver.ContainerDriverActor.reply(ContainerDriverActor.scala:42) [vamp-core.jar:0.7.10]
    at io.vamp.common.akka.ReplyActor$$anonfun$receive$1.applyOrElse(ReplyActor.scala:19) [vamp-core.jar:0.7.10]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [vamp-core.jar:0.7.10]
    at io.vamp.core.container_driver.ContainerDriverActor.aroundReceive(ContainerDriverActor.scala:29) [vamp-core.jar:0.7.10]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [vamp-core.jar:0.7.10]
    at akka.actor.ActorCell.invoke(ActorCell.scala:487) [vamp-core.jar:0.7.10]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [vamp-core.jar:0.7.10]
    at akka.dispatch.Mailbox.run(Mailbox.scala:220) [vamp-core.jar:0.7.10]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [vamp-core.jar:0.7.10]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [vamp-core.jar:0.7.10]
![screenshot from 2015-09-22 15 03 16](https://cloud.githubusercontent.com/assets/1044538/10014892/0b4d57b4-613a-11e5-82f4-d519daa2618c.png)

**Comment by dragoslav** [comment]
Hi @shaluz, it seems Vamp is not configured correctly based on the screenshot and errors you get. Did you follow one of our tutorials (for instance http://vamp.io/documentation/installation/quick_start/)? Vamp has several components and dependencies and probably that docker quick start is the easiest way to start with Vamp.

**Comment by shaluz** [comment]
Yes, I followed the same tutorial. I am using Ubuntu 14.04. Hence first followed the steps in 1.http://vamp.io/installation/ubuntu/
2.Installed Docker(Docker version 1.8.2, build 0a8c2e3)
3.Set the variables 
DOCKER_HOST=tcp://localhost:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/home/ubuntu/.docker/zone1/
4.Executed command :
docker run magneticio/vamp-docker:latest
